language: node_js

jobs:
  include:
    - node_js: 12
      script:
        - echo "build & test" > bundle.txt
        - ls -la
        - node -v
    - node_js: 14
      script:
        - echo "build & test" > bundle.txt
        - ls -la
        - node -v
      workspaces:
        create:
          name: bundle
          paths: .
    - stage: deploy
      node_js: "14"
      workspaces:
        use: bundle
      script:
        - echo "deploy" > deploy.txt
        - ls -la
