language: node_js
node_js:
  - 12
  - 14

script:
  - echo "build & test" > bundle.txt
  - ls -la
  - node -v

jobs:
  include:
    - stage: bundle
      if: node_js == 14
      workspaces:
        create:
          name: bundle
          paths: .
    - stage: deploy
      node_js: "14"
      workspaces:
        use: bundle
      deploy:
        skip_cleanup: true
        provider: script
        script:
          - echo "build & test" > bundle.txt
          - ls -la

stages:
  - bundle
  - name: deploy
    if: branch == master
