language: node_js
node_js:
  - 12
  - 14

script:
  - echo "test" > test.txt
  - ls -la

jobs:
  include:
    - stage: test
      if: node_js = 14
      workspaces:
        create:
          name: bundle
          paths: .
    - stage: deploy
      node_js: 14
      workspaces:
        use: bundle
      deploy:
        skip_cleanup: true
        provider: script
        script:
          - echo "deploy" > deploy.txt
          - ls -la
